sudo: required

language: php

dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.1

env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

addons:
  chrome: stable
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=dev-lib
  - wget http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.1.jar -O selenium-server-standalone.jar && sudo mv selenium-server-standalone.jar /usr/local/bin
  - wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip -O chromedriver.zip && unzip chromedriver.zip && sudo mv chromedriver /usr/local/bin
  - java  -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver  -jar /usr/local/bin/selenium-server-standalone.jar &
  - sleep 3
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh
  - bash bin/install-wp-tests.sh wordpress wordpress_test root '' localhost $WP_VERSION

before_script:
  - "export DISPLAY=:99.0"
  - php /tmp/wp-cli.phar server --path=$WP_CORE_DIR > /dev/null 2>/dev/null &
  - sleep 3
  - vendor/bin/selenium-server-standalone -port 9515 > /dev/null 2>/dev/null &
  - sleep 3
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ln -s $TRAVIS_BUILD_DIR $WP_CORE_DIR/wp-content/plugins/
  - php /tmp/wp-cli.phar plugin activate $(basename $TRAVIS_BUILD_DIR) --path=$WP_CORE_DIR

script:
  - source $DEV_LIB_PATH/travis.script.sh
  - phpunit
  - vendor/bin/codecept run

before_deploy:
  - export RELEASE_FOLDER=contact-widgets
  - php /tmp/wp-cli.phar package install runcommand/dist-archive
  - cp -r ${TRAVIS_BUILD_DIR} /tmp/${RELEASE_FOLDER}
  - mv /tmp/${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}
  - php /tmp/wp-cli.phar dist-archive ${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}/${RELEASE_FOLDER}.zip --format=zip --debug

deploy:
  provider: releases
  api_key:
    secure: HVhuuS7lyf/WweTRSno1c9s1Z/54zHBLRKZVv94ybpHm4zNlG2aFpvWy+bUoLBrr1cCeMN+5HaMMonWETvXMyMsiR+gS/55iC0UsT/EPGhhupJqCZ+hJDk8yucSV0r8le7cy86TR9xLX7OOm6Q5vjPJZlDwyhfYuQBW9c6ciCKbeIXLviomJdBRvNBtHU49JLbP48vCiIBdIBjrFiY17/cSu0PZ9sZDBMOQEc0mPRso7WOTPHSI4tVA6rxKr92x+w6lIhMqBnm4W4o7/UUsRPq2ZPID52LqXpNyk2q8Q76MHBeJoVAscEDb+tCCU+jdwlUfO7/iA+9Fw/5xkYnMfI4bJbTrDN27NCiam4HyMBv63yFyrclPaXbV+bqhf0G5q5+B1eApZ/SiFvD1rYhYSI9fQ7qCini+YEOuW7ilZ1SWmWWqRm7cO8Jve8LZph+hpYfgkGnC+E+ntQAHfQZujZlR+49DJtAOudtPI1WaqBZZH1WsoNFmabiGQs2jkaLveq8798gLAxNrIVT+VvmCs+PGsL3dF7Im3Ohhd92z01bb+ktAOQZjMAP7WqtYSajN2PcaxGTF6ZBkPGBi+Q0Lg5w7dL9RtjO+mtl7rzE85g8bSE65VTli3y9tuEhkQz2PP5p4CnH+L2d6jglU3K+XtRAtk0YvSPQQ5OAt+fqF1Ka4=
  file: contact-widgets.zip
  on:
    tags: true
    repo: godaddy/wp-contact-widgets
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
